<!DOCTYPE html>
<html>
    <body>

        <h2>JavaScript Errors - Throw and Try to Catch</h2>
        
        <p>The <b>try</b> statement lets you test a block of code for errors. In other words, the <b>try</b> statement allows you to define a block of code to be tested for errors while it is being executed.</p>
        <p>The <b>catch</b> statement lets you handle the error. In other words, the <b>catch</b> statement allows you to define a block of code to be executed, if an error occurs in the try block.</p>
        <p>The <b>throw</b> statement lets you create custom errors.</p>
        <p>The <b>finally</b> statement lets you execute code, after try and catch, regardless of the result.</p>
        
        <h3>Errors Will Happen!</h3>
        <p>When executing JavaScript code, different errors can occur. Errors can be coding errors made by the programmer, errors due to wrong input, and other unforeseeable things.</p>
        <p>In this example we have written alert as adddlert to deliberately produce an error:</p>
        
        <p id="demo"></p>

        <h3>JavaScript Throws Errors</h3>
        <p>When an error occurs, JavaScript will normally stop and generate an error message. The technical term for this is: JavaScript will <b>throw an exception (throw an error)</b>.</p>
        <p>JavaScript will actually create an <b>Error object</b> with two properties: <b>name</b> and <b>message</b>.</p>

        <script>
            try {
                adddlert("Welcome guest!");
            }
            catch(err) {
                document.getElementById("demo").innerHTML = err.message;
            }
        </script>
        
    </body>
</html